In [1]:
import numpy as np
from utils import *
from sklearn.preprocessing import PolynomialFeatures
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler as SS

from sklearn.linear_model import LinearRegression, Ridge

In [2]:
X_train, y_train = np.loadtxt('../data/train.dat', usecols=(0,1), unpack=True)
X_test, y_test = np.loadtxt('../data/test.dat', usecols=(0,1), unpack=True)

X_train = X_train.reshape(-1,1)
y_train = y_train.reshape(-1,1)

X_test = X_test.reshape(-1,1)
y_test = y_test.reshape(-1,1)

print(X_train[:5], y_train[:5], sep='\n\n')

[[1998.]
 [2008.]
 [1975.]
 [2004.]
 [1980.]]

[[65.88791334]
 [67.21901249]
 [64.3206674 ]
 [66.92166376]
 [66.11401206]]


In [3]:
model = Pipeline(
    SS(),
    PolynomialFeatures(degree=1),
    SS(),
    RidgeRegressor(λ=1)
)

model.fit(X_train, y_train)
print(model.predictor.w)

[[64.17597825]
 [ 0.54640678]]


In [4]:

from sklearn.preprocessing import StandardScaler as SS

X_trans = PolynomialFeatures(degree=2).fit_transform(X_train)

SS().fit_transform(X_trans)

array([[ 0.        ,  0.21231148,  0.20864331],
       [ 0.        ,  0.87776537,  0.87660107],
       [ 0.        , -1.31823247, -1.31500403],
       [ 0.        ,  0.61158382,  0.60901779],
       [ 0.        , -0.98550553, -0.985277  ],
       [ 0.        ,  0.47849304,  0.47542624],
       [ 0.        ,  0.81121998,  0.80965523],
       [ 0.        , -1.05205092, -1.0512891 ],
       [ 0.        , -0.18696086, -0.19053065],
       [ 0.        , -0.85241475, -0.85315276],
       [ 0.        ,  1.47667388,  1.4806143 ],
       [ 0.        , -0.25350624, -0.25694293],
       [ 0.        , -0.91896014, -0.91923155],
       [ 0.        , -1.18514169, -1.18321326],
       [ 0.        , -1.25168708, -1.24912532],
       [ 0.        , -1.45132325, -1.44666141],
       [ 0.        ,  0.41194765,  0.40868048],
       [ 0.        ,  0.27885687,  0.27528902],
       [ 0.        , -1.38477786, -1.38084939],
       [ 0.        ,  0.54503843,  0.54220534],
       [ 0.        ,  0.6781292 ,  0.675

In [5]:
StandardScaler().fit_transform(X_trans)

array([[ 0.        ,  0.21231148,  0.20864331],
       [ 0.        ,  0.87776537,  0.87660107],
       [ 0.        , -1.31823247, -1.31500403],
       [ 0.        ,  0.61158382,  0.60901779],
       [ 0.        , -0.98550553, -0.985277  ],
       [ 0.        ,  0.47849304,  0.47542624],
       [ 0.        ,  0.81121998,  0.80965523],
       [ 0.        , -1.05205092, -1.0512891 ],
       [ 0.        , -0.18696086, -0.19053065],
       [ 0.        , -0.85241475, -0.85315276],
       [ 0.        ,  1.47667388,  1.4806143 ],
       [ 0.        , -0.25350624, -0.25694293],
       [ 0.        , -0.91896014, -0.91923155],
       [ 0.        , -1.18514169, -1.18321326],
       [ 0.        , -1.25168708, -1.24912532],
       [ 0.        , -1.45132325, -1.44666141],
       [ 0.        ,  0.41194765,  0.40868048],
       [ 0.        ,  0.27885687,  0.27528902],
       [ 0.        , -1.38477786, -1.38084939],
       [ 0.        ,  0.54503843,  0.54220534],
       [ 0.        ,  0.6781292 ,  0.675

In [10]:
print(X_trans[:5])

apply_per_dim = lambda f, X: np.array([f(X[:, d]) for d in range(X.shape[1])])

mean = apply_per_dim(np.mean, X_trans)
std = apply_per_dim(np.std, X_trans)
std[std==0] = 1

print(SS().fit_transform(X_trans)[:5])

((X_trans - mean) / std)[:5] * std + mean

[[1.000000e+00 1.998000e+03 3.992004e+06]
 [1.000000e+00 2.008000e+03 4.032064e+06]
 [1.000000e+00 1.975000e+03 3.900625e+06]
 [1.000000e+00 2.004000e+03 4.016016e+06]
 [1.000000e+00 1.980000e+03 3.920400e+06]]
[[ 0.          0.21231148  0.20864331]
 [ 0.          0.87776537  0.87660107]
 [ 0.         -1.31823247 -1.31500403]
 [ 0.          0.61158382  0.60901779]
 [ 0.         -0.98550553 -0.985277  ]]


array([[1.000000e+00, 1.998000e+03, 3.992004e+06],
       [1.000000e+00, 2.008000e+03, 4.032064e+06],
       [1.000000e+00, 1.975000e+03, 3.900625e+06],
       [1.000000e+00, 2.004000e+03, 4.016016e+06],
       [1.000000e+00, 1.980000e+03, 3.920400e+06]])