In [1]:
import numpy as np
from utils import *
from matplotlib import pyplot as plt

In [2]:
X_train, y_train = np.loadtxt('../data/train.dat', usecols=(0,1), unpack=True)
X_test, y_test = np.loadtxt('../data/test.dat', usecols=(0,1), unpack=True)
X_train = X_train.reshape(-1,1)
y_train = X_test.reshape(-1,1)
X_test = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [3]:
model = Pipeline(
    StandardScaler(),
    PolynomialFeatures(d=0),
    StandardScaler(),
    RidgeRegressor(λ=0)
)


In [4]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
scaler = StandardScaler()
X_trans = scaler.fit_transform(X_train)
X_trans = poly.fit_transform(X_trans)
X_trans = scaler.fit_transform(X_trans)

# print(X_train)
print(X_trans)

[[ 0.36244984 -0.49404289 -0.67588613]
 [ 0.36244984  0.22953808  0.11287273]
 [ 0.36244984 -2.15827911  1.16462765]
 [ 0.36244984 -0.05989431 -0.31819316]
 [ 0.36244984 -1.79648863  0.33115716]
 [ 0.36244984 -0.2046105  -0.47594493]
 [ 0.36244984  0.15717998 -0.00933903]
 [ 0.36244984 -1.86884673  0.47859087]
 [ 0.36244984 -0.92819147 -0.68689207]
 [ 0.36244984 -1.65177244  0.06518034]
 [ 0.36244984  0.88076095  1.64613742]
 [ 0.36244984 -1.00054957 -0.65502071]
 [ 0.36244984 -1.72413053  0.19335365]
 [ 0.36244984 -2.01356292  0.80234887]
 [ 0.36244984 -2.08592102  0.97867316]
 [ 0.36244984 -2.30299531  1.56542721]
 [ 0.36244984 -0.2769686  -0.54037552]
 [ 0.36244984 -0.42168479 -0.64034612]
 [ 0.36244984 -2.23063721  1.36021233]
 [ 0.36244984 -0.13225241 -0.40188414]
 [ 0.36244984  0.01246379 -0.22487198]
 [ 0.36244984 -0.85583337 -0.70913323]
 [ 0.36244984 -1.21762386 -0.50162545]
 [ 0.36244984 -0.78347528 -0.7217442 ]
 [ 0.36244984 -0.56640099 -0.70179594]
 [ 0.36244984  0.95311904